### ISSUE TITLE
Do we need to pass pritunl volume? 

### ISSUE THREAD

**Issue by rishiloyola** [jippi/docker-pritunl#10]
I am facing certain problems when I didn't pass pritunl volume(`/var/lib/pritunl`) while recovering after a server crash. 
Does pritunl need persistent file system?

**Comment by myoung34** [comment]
It does not, all persistent data outside of logs go to mongo.

If youre running mongo locally (via that container) then yes.

**Comment by jippi** [comment]
I've expanded on that in the README now 

https://github.com/jippi/docker-pritunl#usage-with-embedded-mongodb
