### ISSUE TITLE
Removing the need to create pritunl.conf before running the container for the first time

### ISSUE THREAD

**Issue by melikyuksel** [jippi/docker-pritunl#12]
Is it not possible to move the pritunl.conf file to its own directory so that it doesn't have to be manually created before running this container for the first time? Since Docker doesn't (yet?) allow container single files to be copied to the host, this is necessary since pritunl.conf is in /etc/ with a bunch of other files that we're not interested in making persistent.

**Comment by jippi** [comment]
Hi,

If you pass `-e PRITUNL_DONT_WRITE_CONFIG=1` to your docker command env, then it's not

you should also be able to do `-v /etc/pritunl.conf:/etc/pritunl.conf` with a docker volume mount to only specify that one file - can be a different location on your host instance if you prefer
