### ISSUE TITLE
Clarify privileged requirement

### ISSUE THREAD

**Issue by martenjacobs** [jippi/docker-pritunl#19]
Could you please clarify in the documentation why it's required to run this container privileged? I just tried running it without and it seems to work up to the point where you start the server. At that point it looks like nothing happens (although no error message is shown). I'd prefer to keep the number of privileged containers to a minimum so I'd like to know why this is a requirement and if there's any way around it.

**Comment by jippi** [comment]
I never really dug into it, but i never got it working without it - I assume its because it needs to manipulate routing tables and firewall rules to function :)
