### ISSUE TITLE
recommended mongodb migration

### ISSUE THREAD

**Issue by realies** [jippi/docker-pritunl#22]
what is a recommended way to upgrade to the latest tag? noticed mongodb has changed versions and it currently does not start using old volume files

**Comment by jippi** [comment]
Hey! :) 

The steps in the official documentation should do the trick:) 

https://www.mongodb.com/docs/manual/release-notes/5.0-upgrade-standalone/

**Comment by jippi** [comment]
@realies So, I ended up being bitten by the upgrade path being kinda annoying today with a client, so made this new section in the (brand new README) file that explains how to do it, and a script that can do it for you 

Please let me know what you think 👍 

https://github.com/jippi/docker-pritunl#upgrading-mongodb

**Comment by realies** [comment]
thanks a lot for the guide and script, @jippi - will certainly help a lot of noobs

**Comment by jippi** [comment]
No worries :) It honestly wasn't my attention to break everyones VPN solution by upgrading Mongo without afterthought - I assumed wrongly that mongo single node would just auto-upgrade - but wasn't the case :(
