### ISSUE TITLE
Cannot Start after Deployment

### ISSUE THREAD

**Issue by zengrotrust** [jippi/docker-pritunl#25]
Hello. I deployed via docker compose. The container created successfully but only one line of log is showing: 
No log line matching the '' filter

Files in the volumes looks correct.
│   ├── index-55-7996217468716057611.wt
│   ├── index-57-7996217468716057611.wt
│   ├── index-5-7996217468716057611.wt
│   ├── index-58-7996217468716057611.wt
│   ├── index-59-7996217468716057611.wt
│   ├── index-60-7996217468716057611.wt
│   ├── index-61-7996217468716057611.wt
│   ├── index-62-7996217468716057611.wt
│   ├── index-64-7996217468716057611.wt
│   ├── index-65-7996217468716057611.wt
│   ├── index-66-7996217468716057611.wt
│   ├── index-67-7996217468716057611.wt
│   ├── index-6-7996217468716057611.wt
│   ├── index-69-7996217468716057611.wt
│   ├── index-70-7996217468716057611.wt
│   ├── index-71-7996217468716057611.wt
│   ├── index-73-7996217468716057611.wt
│   ├── index-74-7996217468716057611.wt
│   ├── index-76-7996217468716057611.wt
│   ├── index-77-7996217468716057611.wt
│   ├── index-79-7996217468716057611.wt
│   ├── index-80-7996217468716057611.wt
│   ├── index-81-7996217468716057611.wt
│   ├── index-83-7996217468716057611.wt
│   ├── index-84-7996217468716057611.wt
│   ├── index-86-7996217468716057611.wt
│   ├── index-87-7996217468716057611.wt
│   ├── index-8-7996217468716057611.wt
│   ├── index-89-7996217468716057611.wt
│   ├── index-90-7996217468716057611.wt
│   ├── index-92-7996217468716057611.wt
│   ├── index-93-7996217468716057611.wt
│   ├── index-94-7996217468716057611.wt
│   ├── index-95-7996217468716057611.wt
│   ├── index-97-7996217468716057611.wt
│   ├── index-98-7996217468716057611.wt
│   ├── index-99-7996217468716057611.wt
│   ├── journal  [error opening dir]
│   ├── _mdb_catalog.wt
│   ├── mongod.lock
│   ├── sizeStorer.wt
│   ├── storage.bson
│   ├── WiredTiger
│   ├── WiredTigerHS.wt
│   ├── WiredTiger.lock
│   ├── WiredTiger.turtle
│   └── WiredTiger.wt
├── pritunl
│   ├── pritunl.uuid
│   └── setup_key
└── pritunl.conf

version: '3.3'
services:
    pritunl:
        container_name: pritunl
        image: ghcr.io/jippi/docker-pritunl
        restart: unless-stopped
        privileged: true
        ports:
            - '1080:80'
            - '1443:443'
            - '1194:1194'
            - '1194:1194/udp'
        dns:
            - 127.0.0.1
        volumes:
            - '/home/administrator/pritunl/data/pritunl.conf:/etc/pritunl.conf'
            - '/home/administrator/pritunl/data/pritunl:/var/lib/pritunl'
            - '/home/administrator/pritunl/data/mongodb:/var/lib/mongodb'

Please help!

**Comment by jippi** [comment]
did you perhaps need to upgrade your mongodb? https://github.com/jippi/docker-pritunl#upgrading-mongodb
