### ISSUE TITLE
EXPOSE 1194/udp missing

### ISSUE THREAD

**Issue by theasp** [jippi/docker-pritunl#3]
I couldn't get UDP working on 1194 despite forwarding 1194/udp, but it works after exposing 1194/udp.  I am guessing that because it has `EXPOSE 1194` it doesn't automatically expose 1194/udp.

**Comment by jippi** [comment]
https://github.com/jippi/docker-pritunl/blob/master/Dockerfile#L27  need to be with both /tcp and /udp ? PR welcome if that is the case :)

**Comment by theasp** [comment]
This should be fixed with the change you merged.  Thank you.
