### ISSUE TITLE
访问web报错ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by fengqing11** [jippi/docker-pritunl#31]
![image](https://github.com/jippi/docker-pritunl/assets/45026131/ae75f5b2-b899-44bb-8325-f8a4594c62a6)

访问443
![image](https://github.com/jippi/docker-pritunl/assets/45026131/3cc6021d-0e0c-43d9-b0cc-23dd00928a6b)

**Comment by jippi** [comment]
Sorry, I don't speak Chinese; please use English :) 

Guessing from screenshots you need to use `https://localhost:8443` instead of `http://localhost:8443` (notice the `s` in `httpS://`
