### ISSUE TITLE
MongoDB upgrade 5.0 -> 6.0

### ISSUE THREAD

**Issue by Auburn** [jippi/docker-pritunl#32]
If I want to switch from `latest-focal` tag to `latest` tag do I need to upgrade the existing Mongo DB from 5.0 -> 6.0 manually? The readme only specifies upgrades up to 5.0

Thanks

**Comment by jippi** [comment]
Currently, yes, though the script (https://github.com/jippi/docker-pritunl/blob/master/mongo-upgrade.sh) might just need a new UPGRADE_PATH item for 6 to work (I haven't tested this) - feel free to give it a shot and let me know :)
