### ISSUE TITLE
How to obtain a WireGuard file via the Pritunl API?

### ISSUE THREAD

**Issue by velrino** [jippi/docker-pritunl#33]
Hi

I’m creating a project in React Electron that will use OpenVPN and WireGuard as features.

I would like to know how to connect using WireGuard user configuration file?

![image](https://github.com/user-attachments/assets/c6f84992-9ef3-4a38-ab40-0e33606304fb)

**Comment by jippi** [comment]
Hey, please ask Pritunl support questions here: https://github.com/pritunl/pritunl
